project_id = "nvpoprqufydeozwpzbpm"

[functions.submit-test]
verify_jwt = false
timeout = 180

[functions.send-email]
verify_jwt = false

[functions.fetch-results]
verify_jwt = false

[functions.submit-waitlist]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.check-existing-test]
verify_jwt = false

[functions.analyze-website]
verify_jwt = false
timeout = 180

[functions.submit-beta-application]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.get-blog-test-count]
verify_jwt = false

[functions.validate-llms-txt]
verify_jwt = false
