project_id = "nvpoprqufydeozwpzbpm"

[functions.submit-test]
verify_jwt = false
timeout = 180

[functions.send-email]
verify_jwt = false

[functions.fetch-results]
verify_jwt = false

[functions.submit-waitlist]
verify_jwt = false